/**
 * industrialworld -- standalone LuaJIT binary wrapper
 *
 * Embeds ahead-of-time compiled LuaJIT bytecode and runs it via the
 * LuaJIT C API. Statically links BearLibTerminal (which in turn pulls
 * FreeType + PicoPNG via its CMake build). BearLibTerminal symbols are
 * exported from the executable (-Wl,-export_dynamic) so the Lua-side
 * FFI can resolve them through ffi.C.
 *
 * Architecture mirrors the "cursed" wrapper: the C side is a thin host
 * that preloads bytecode modules into package.preload and hands control
 * to the Lua entry point. BLT owns the window, but Lua drives the
 * per-frame render/input loop (BLT's CocoaWindow is patched to not
 * enter [NSApp run]), so there's no blocking event-pump on the C side.
 *
 * Build with: just build   (produces a static binary)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luajit.h>

/* Auto-generated bytecode headers */
#include "includes.inc"

/* Bundled BearLibTerminal declarations (only the C symbols touched from C). */
#include "vendor.h"

/* ── Module table (auto-generated) ──────────────────────────────── */

static const struct {
    const char *name;
    const char *bytecode;
    size_t      bytecode_len;
} modules[] = {
#include "modules.inc"
    { NULL, NULL, 0 }
};

/* ── Preload ─────────────────────────────────────────────────────── */

static int preload_modules(lua_State *L)
{
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");

    for (int i = 0; modules[i].name != NULL; i++) {
        int status = luaL_loadbuffer(
            L,
            modules[i].bytecode,
            modules[i].bytecode_len,
            modules[i].name
        );
        if (status != LUA_OK) {
            fprintf(stderr, "industrialworld: failed to preload %s: %s\n",
                    modules[i].name, lua_tostring(L, -1));
            lua_pop(L, 1);
            continue;
        }
        lua_setfield(L, -2, modules[i].name);
    }

    lua_pop(L, 2); /* pop preload and package */
    return 0;
}

/* ── State setup ─────────────────────────────────────────────────── */

static lua_State *create_state(void)
{
    lua_State *L = luaL_newstate();
    if (L == NULL) {
        fprintf(stderr, "industrialworld: failed to create Lua state\n");
        return NULL;
    }
    luaL_openlibs(L);
    preload_modules(L);
    return L;
}

static void setup_globals(lua_State *L, int argc, char *argv[])
{
    /* Push argv as the global "arg" */
    lua_createtable(L, argc, 1);
    for (int i = 0; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i);
    }
    lua_setglobal(L, "arg");
}

/* ── Find entry point ────────────────────────────────────────────── */

static const char *find_module(const char *name, size_t *out_len)
{
    for (int i = 0; modules[i].name != NULL; i++) {
        if (strcmp(modules[i].name, name) == 0) {
            *out_len = modules[i].bytecode_len;
            return modules[i].bytecode;
        }
    }
    return NULL;
}

/* ── Run main module ─────────────────────────────────────────────── */

static int run_main(lua_State *L)
{
    size_t main_len = 0;
    const char *main_bc = find_module("main", &main_len);

    if (main_bc == NULL) {
        fprintf(stderr, "industrialworld: no main module found\n");
        return -1;
    }

    int status = luaL_loadbuffer(L, main_bc, main_len, "industrialworld");
    if (status != LUA_OK) {
        fprintf(stderr, "industrialworld: failed to load bytecode: %s\n", lua_tostring(L, -1));
        return -1;
    }

    status = lua_pcall(L, 0, 1, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "industrialworld: runtime error: %s\n", lua_tostring(L, -1));
        return -1;
    }

    if (lua_isnumber(L, -1))
        return (int)lua_tointeger(L, -1);

    return 0;
}

/* ── Entry ───────────────────────────────────────────────────────── */

int main(int argc, char *argv[])
{
    lua_State *L = create_state();
    if (L == NULL) {
        return EXIT_FAILURE;
    }
    setup_globals(L, argc, argv);

    int exit_code = run_main(L);

    lua_close(L);

    /* Ensure BearLibTerminal is torn down even if Lua forgot to. */
    tcow_quit_safe();

    return exit_code < 0 ? EXIT_FAILURE : exit_code;
}
